modLoader="javafml"
loaderVersion="[38,)"
license="MIT"
issueTrackerURL="https://github.com/vladislemon/torch-key-forge/issues"
[[mods]]
modId="torch_key_forge"
version="${file.jarVersion}"
displayName="Torch Key"
displayURL="https://www.curseforge.com/minecraft/mc-mods/torch-key-forge"
logoFile="icon.png"
credits="This mod is forge version of https://www.curseforge.com/minecraft/mc-mods/torchkey"
authors="vladislemon"
description='''
Adds a hotkey to place a torch from your hotbar.
'''
